fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    registration:
        form:
            type: App\Form\Security\RegistrationFormType
    profile:
        form:
            type: App\Form\Profile\ProfileFormType
    from_email:
        address: "ceo@vaderlab.com"
        sender_name: "Stanislau Komar"
