rollerworks_password_strength:
    blacklist:
        # Replace rollerworks_password_strength.blacklist.provider.noop with the service-id of the provider you want to use
        default_provider: rollerworks_password_strength.blacklist.provider.noop
