version: '3.1'

services:
  oauth_db:
    image: mysql:8.0.11
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaderlab_oauth
      MYSQL_USER: vaderlab
      MYSQL_PASSWORD: vaderlab
    volumes:
      - ./var/lib/mysql/:/var/lib/mysql
    networks:
      - vaderlab

  oauth_php:
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    volumes:
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      - ./:/source
      - ./etc/php/fpm/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
      - ./var/log/php:/var/log/php
    working_dir: /source
    depends_on:
      - oauth_db
    networks:
      - vaderlab

  oauth_web:
    image: nginx:alpine
    working_dir: /source
    volumes:
      - ./var/log/nginx:/var/log/nginx/
      - ./etc/nginx/conf.d/accounts.conf:/etc/nginx/conf.d/accounts.conf
      - ./:/source
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=accounts.vaderlab.com
      - NGINX_PORT=80
    depends_on:
      - oauth_php
    networks:
      - vaderlab


networks:
  vaderlab:
    driver: bridge

